### ISSUE TITLE
Resizing game window causes crash

### ISSUE THREAD

**Issue by peter-r-g** [xezno/mocha#14]
When resizing the game window (dragging from borders, maximize button, or double-clicking to maximize) causes a crash in Vulkan validation. The call stack from the crash in the video is on Pastebin [here](https://pastebin.com/RgDyLZdc).

https://user-images.githubusercontent.com/11802285/211907297-df40235b-31be-4267-a565-510c03cfdc87.mp4

**Comment by xezno** [comment]
I don't get this on my machine but I do get a couple of validation errors, a5afa8017a1a6d4d9e6549e44b889595ce8df312 fixes one of them by deferring the deletion of old render targets until after the frame ends. That may (or may not..) help. I'll take a look at the other validation error too in a minute.

**Comment by peter-r-g** [comment]
a5afa80 fixes the issue I had. Thank you!

https://user-images.githubusercontent.com/11802285/211945201-18cfb819-7924-4ffa-8b54-33f53333520a.mp4
