### ISSUE TITLE
Vulkan race condition crash

### ISSUE THREAD

**Issue by peter-r-g** [xezno/mocha#15]
Lately, I have been getting a rare crash when debugging Mocha. It will happen on startup and not be consistent. Looking through the call stack (available on Pastebin [here](https://pastebin.com/WSxHzkRp)) I see mentions of threading so I assume it is some kind of race condition that causes it to happen.

**Comment by xezno** [comment]
I think I fixed this with https://github.com/xezno/mocha/commit/8c89315289d14c86e19f6489f2dd2197f8ab421d. If it's not fixed then re-open this issue and let me know.
