### ISSUE TITLE
Game window is blank

### ISSUE THREAD

**Issue by peter-r-g** [xezno/mocha#17]
For the last 2-3 days my game window has just been a black screen. The debug overlay and editor-related items still show but the actual scene is never there. Checking the entity list everything still seems to be there but just not rendering. The only thing that I have seen in the console regarding this is what seem to be errors in the `RenderManager::RenderMesh`:
![image](https://user-images.githubusercontent.com/11802285/212208077-251eed29-6bd5-4792-ac1f-e9f62805c930.png)

**Comment by xezno** [comment]
Those aren't errors - just debug messages. I should probably make that clearer in the console UI.

I think this has something to do with the switch to rendering to a full screen triangle, though I'm not sure why it'd work for me and not for you. I'll look into this tomorrow.

**Comment by xezno** [comment]
Should be fixed in https://github.com/xezno/mocha/commit/23ee4ef7e9d34a4f33412b779e2838163d8040e2 🙂
