### ISSUE TITLE
Hotloading throws when upgrading instances of abstract classes

### ISSUE THREAD

**Issue by MuffinTastic** [xezno/mocha#28]
## Reproduction

1. Put this in Game.cs

```cs
// ...

public abstract class Abstract { }

public class Implementation : Abstract
{
	public int Field;
	public string Property { get; set; }
}

public class Game : BaseGame
{
	// ...

	public Abstract _instance;

	public override void Startup()
	{
		// ...

		_instance = new Implementation
		{
			Field = 123,
			Property = "!olleH dlroW"
		};

		// ...
	}

	// ...
}
```

2. Start Mocha, wait for the game to start
3. Save Game.cs to trigger a hotload
4. Witness
![image](https://user-images.githubusercontent.com/10884425/214757515-914d5e66-a0ac-493b-b953-0cead8c2e1d1.png)

## Notes

Abstract classes and their implementations can obviously be from different assemblies, not sure what a clean way to handle that would be. Maybe something like this would work:

1. If the old implementation type is from the assembly we're swapping out, attempt to get a class of the same name from the new assembly and instantiate that
2. Else, just make a new instance of the old implementation type (It's probably from some .NET or Mocha assembly or something)

Just spitballing though

**Comment by xezno** [comment]
Think I fixed this in https://github.com/xezno/mocha/commit/7207eee41826ebe65e0ad96c3399693dc7a5a5b1, please re-open if that's not the case
