### ISSUE TITLE
Hotloading throws when upgrading between types that can't be implicitly cast 

### ISSUE THREAD

**Issue by MuffinTastic** [xezno/mocha#30]
## Reproduction

1. Put this in Game.cs
```cs

public class Game : BaseGame
{
	// ...

	class Kaboom
	{
		public string Stuff;
	}

	private int _testField;

	public override void Startup()
	{
		// ...

		_testField = 123;

		// ...
	}

	// ...
}
```
2. Start Mocha, wait for the game to start
3. Change
```cs
private int _testField;
```
to
```cs
private Kaboom _testField;
```
and remove the `_testField = 123;` line from `Startup()` so that it will compile
4. Save Game.cs to trigger a hotload
5. Kaboom
![image](https://user-images.githubusercontent.com/10884425/214775032-b2aff3b2-f703-411a-9736-52bd8fe7cf61.png)

**Comment by xezno** [comment]
Think I fixed this in https://github.com/xezno/mocha/commit/29579d576ec540338ff69d2a1e24ca3ccb5bdb75, please re-open if that's not the case
