### ISSUE TITLE
Licensing stuff

### ISSUE THREAD

**Issue by MuffinTastic** [xezno/mocha#40]
AGPLv3 is an elaboration/extension of the GPL, and the GPL is moderately contentious. Of course, I'm not a lawyer, but from my understanding of the situation there's disagreement about what legally qualifies as "modification" even after several decades, and specifically whether or not that definition includes dynamic linking. If it _does_ include dynamic linking then anyone that uses Mocha would also be regarded as "modifying" it, and thus be bound by the GPL to make their game open-source. It may harm adoption of the engine in commercial spheres. Is this the intended effect?

The LGPL seems more permissive. It would require that people make modifications to the engine open-source, but their own game could remain closed-source if they so wished. I think.

<https://choosealicense.com/licenses>
<https://choosealicense.com/appendix>

**Comment by Xenthio** [comment]
GPL sucks. consider BSD or MIT

**Comment by xezno** [comment]
GPL is there because I would rather someone didn't take the engine itself and sell it, or use parts of it in a commercial application, without providing source code of their own in return.

LGPL looks like the best choice here so I will consider switching to that.
