### ISSUE TITLE
Runtime errors

### ISSUE THREAD

**Issue by peter-r-g** [xezno/mocha#8]
With #4 completed I can now run Mocha but it is shortlived. Due to my lack of knowledge in C++ I have not been able to get very far in this process but I will detail what I have managed to find so far:

## cvarmanager/gamesettings - cvars.json is null
~~The first error that comes, `cvarFile` appears to be in some kind of null state. I had thought that maybe it was because there is no `cvars.json` file in the "build" directory but even creating it seems to produce the same error. For now, to skip past the error I just added the following after constructing the ifstream object:~~
```cpp
if ( !cvarFile.good() )
    return;
```

~~The second error is the exact same but for gamesettings.~~

## Vulkan validation error
After skipping the first two errors I get the following error from Vulkan:
```
[ERROR: Validation]
Validation Error: [ VUID-vkGetPhysicalDeviceSurfaceSupportKHR-surface-parameter ] Object 0: handle = 0x24ddddb99e0, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0x801f247e | Invalid VkSurfaceKHR Object 0xcccccccccccccccc. The Vulkan spec states: surface must be a valid VkSurfaceKHR handle (https://vulkan.lunarg.com/doc/view/1.3.224.1/windows/1.3-extensions/vkspec.html#VUID-vkGetPhysicalDeviceSurfaceSupportKHR-surface-parameter)
[ERROR: Validation]
Validation Error: [ UNASSIGNED-Threading-Info ] Object 0: handle = 0xcccccccccccccccc, type = VK_OBJECT_TYPE_SURFACE_KHR; | MessageID = 0x5d6b67e2 | Couldn't find VkSurfaceKHR Object 0xcccccccccccccccc. This should not happen and may indicate a bug in the application.
```

Callstack information is on Pastebin [here](https://pastebin.com/hgTm2eNz)

That is as far as I have gotten so far. As problems get solved I will keep digging.

**Comment by peter-r-g** [comment]
> ## cvarmanager/gamesettings - cvars.json is null
> The first error that comes, `cvarFile` appears to be in some kind of null state. I had thought that maybe it was because there is no `cvars.json` file in the "build" directory but even creating it seems to produce the same error. For now, to skip past the error I just added the following after constructing the ifstream object:
> 
> ```c++
> if ( !cvarFile.good() )
>     return;
> ```
> 
> The second error is the exact same but for gamesettings.

Turns out the current working directory when launching from VS is the Native > Host project so disregard :)

The Vulkan error still persists and is where I am current at.

**Comment by xezno** [comment]
Forgot to mention it but https://github.com/xezno/mocha/commit/23c52ac7cb64fa543e302ae80b1bcf24c57c6df3 should've fixed it - let me know if that's the case

**Comment by peter-r-g** [comment]
That fixed it, I am now able to launch Mocha fully. Got a few things to note:

![Capture](https://user-images.githubusercontent.com/11802285/211049360-9fe1faa8-5de0-4397-8d1b-c5c93eeab817.PNG)

### cvars.json
With the issue of the cvarmanager/gamesettings crashing because of no cvars.json it should probably check if the stream is good and warn the user if it is not so it does not crash with little info to the user.

### Content directory
After getting past the Vulkan validation error the game bailed on trying to load a font. The problem was that I did not copy the content directory over. It should probably check if the content directory exists and bail with a more friendly error to the user.

### spacegame.json incorrect path
The spacegame.json for the `managed > path` property has ".\\build\\Engine" but since the file needs to be copied to the build directory that path becomes invalid. It should just be ".\\Engine".

### GPU not detected
Not sure how bad of an issue this is but looking at the screenshot it looks like Mocha cannot find the GPU I use. I currently use an MSI Geforce RTX 2070 super

### Vulkan validation error opening console
When I open the console widget I get endlessly spammed with the following validation error:
```
[ERROR: Validation]
Validation Error: [ VUID-VkPresentInfoKHR-pImageIndices-01296 ] Object 0: handle = 0x2c55811c9b0, type = VK_OBJECT_TYPE_QUEUE; | MessageID = 0xc7aabc16 | vkQueuePresentKHR(): pSwapchains[0] images passed to present must be in layout VK_IMAGE_LAYOUT_PRESENT_SRC_KHR or VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR but is in VK_IMAGE_LAYOUT_UNDEFINED. The Vulkan spec states: Each element of pImageIndices must be the index of a presentable image acquired from the swapchain specified by the corresponding element of the pSwapchains array, and the presented image subresource must be in the VK_IMAGE_LAYOUT_PRESENT_SRC_KHR layout at the time the operation is executed on a VkDevice (https://github.com/KhronosGroup/Vulkan-Docs/search?q=)VUID-VkPresentInfoKHR-pImageIndices-01296)
```
As far as I can tell it does not seem to break anything.

### Mouse unusable
In spacegame it seems that my mouse does not do anything. I do not see any information in the console relating to the mouse so I cannot give much information about that.

### Unable to close through the main window
The close button on the main window does not function. The only way to close the game is by closing the terminal window.

**Comment by xezno** [comment]
Awesome! Thank you for your patience, I'm glad you got the engine working (mostly).

> ### cvars.json
> With the issue of the cvarmanager/gamesettings crashing because of no cvars.json it should probably check if the stream is good and warn the user if it is not so it does not crash with little info to the user.

Very true, it would probably be best to just skip loading if it doesn't exist since some default values are provided anyway where there are missing cvar values.

> ### Content directory
> After getting past the Vulkan validation error the game bailed on trying to load a font. The problem was that I did not copy the content directory over. It should probably check if the content directory exists and bail with a more friendly error to the user.

The content directory in the root folder should be the one used when launching because the working directory is set to the root folder.. I'm not sure if I missed something there but launching Mocha should effectively launch it as if it were in "." rather than ".\Build"

> ### spacegame.json incorrect path
> The spacegame.json for the `managed > path` property has ".\build\Engine" but since the file needs to be copied to the build directory that path becomes invalid. It should just be ".\Engine".

I think this is the same issue as above - I'll have a look at the project

> ### GPU not detected
> Not sure how bad of an issue this is but looking at the screenshot it looks like Mocha cannot find the GPU I use. I currently use an MSI Geforce RTX 2070 super

I think I might've messed up something with C++ -> C# string interop, I'll have a look at this. It looks like it might be freeing the memory before the managed context has a chance to actually use it to display the GPU name.
This isn't used for anything important, fortunately - it's just a display value

> ### Vulkan validation error opening console
> When I open the console widget I get endlessly spammed with the following validation error:
> 
> ```
> [ERROR: Validation]
> Validation Error: [ VUID-VkPresentInfoKHR-pImageIndices-01296 ] Object 0: handle = 0x2c55811c9b0, type = VK_OBJECT_TYPE_QUEUE; | MessageID = 0xc7aabc16 | vkQueuePresentKHR(): pSwapchains[0] images passed to present must be in layout VK_IMAGE_LAYOUT_PRESENT_SRC_KHR or VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR but is in VK_IMAGE_LAYOUT_UNDEFINED. The Vulkan spec states: Each element of pImageIndices must be the index of a presentable image acquired from the swapchain specified by the corresponding element of the pSwapchains array, and the presented image subresource must be in the VK_IMAGE_LAYOUT_PRESENT_SRC_KHR layout at the time the operation is executed on a VkDevice (https://github.com/KhronosGroup/Vulkan-Docs/search?q=)VUID-VkPresentInfoKHR-pImageIndices-01296)
> ```
> 
> As far as I can tell it does not seem to break anything.

I believe this is a problem with ImGUI. It's probably got something to do with the [patches I did](https://github.com/xezno/imgui) in order to update ImGUI to work with Vulkan's new dynamic rendering feature. It looks like I need to transition the layout in ImGUI itself somewhere - the messages are harmless but this is definitely something I will look at.

> ### Mouse unusable
> In spacegame it seems that my mouse does not do anything. I do not see any information in the console relating to the mouse so I cannot give much information about that.

Hitting F10 will toggle cursor lock / unlock so that you can switch between tools and game.. this obviously isn't intuitive at all so I'll change that to tilde and add a note in the status bar.

> ### Unable to close through the main window
> The close button on the main window does not function. The only way to close the game is by closing the terminal window.

Yeah I forgot to re-add window closing after the rendering refactor, I'll add that back in shortly.

**Comment by peter-r-g** [comment]
As #10 mentions, the options in the debugging configuration were missing so it was defaulting the CWD to the project directory. Changing those options for some reason saves them to the user specific file for the project (`Host.vcxproj.user`) which is ignored by the [.gitignore](https://github.com/xezno/mocha/blob/master/.gitignore#L9). It is possible that there could be more configuration settings in your user-specific file that need to be brought into the main vcxproj.

**Comment by xezno** [comment]
Merged that, I'm assuming this all works for you now?

**Comment by peter-r-g** [comment]
Yeah other than the `cvars.json`, `GPU not detected`, `Vulkan validation error opening console`, and `Unable to close through the main window` sections. Those can just be their own issues so I will close this and open a few covering the rest.

Thanks for the help!

**Comment by xezno** [comment]
Those four are fixed on the dev branch, I just haven't merged it in yet. Will do that in a minute
